site_name: Nameless
theme: readthedocs
site_url: http://docs.namelessmc.com
repo_url: https://github.com/NamelessMC
pages:
- 'Home': 'index.md'
- User Guide:
    - 'Index': 'user-guide/index.md'
- Developer Guide:
    - 'Index': 'developer-guide/index.md'
- About:
    - 'Index': 'about/index.md'
    - 'License': 'about/license.md'
    - 'Release Notes': 'about/release-notes.md'